# Generated by Django 4.2 on 2023-04-10 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Income', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Source',
        ),
    ]
